### PR TITLE
chore: DBTP-768 - Publish to PyPi

### PR DESCRIPTION
**Pull request by JohnStainsby**
Not much to see here, just re-enabling the PyPi publish.

The main change is that the [CodeBuild job](https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/763451185160/projects/platform-tools-pypi/history?region=eu-west-2&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ) for `buildspec.pypi.yml` now triggers on release. I have updated `buildspec.test.yml` [CodeBuild job](https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/763451185160/projects/platform-tools-test/history?region=eu-west-2&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ) to still run the tests on push to main.

### CODE REVIEW

**Comment by gabelton** [comment]
Is there a gitlab PR for the change to the codebuild job?

**Review by samuele-mattiuzzo — APPROVED** [review]

**Comment by JohnStainsby** [comment]
@gabelton 
> Is there a gitlab PR for the change to the codebuild job?

No... but it sounds like there should be 😅 I'm not sure I can see the relevant project in GitLab, do you know which one it is?

**Comment by gabelton** [comment]
> @gabelton
> 
> > Is there a gitlab PR for the change to the codebuild job?
> 
> No... but it sounds like there should be 😅 I'm not sure I can see the relevant project in GitLab, do you know which one it is?

Could be a misunderstanding on my part, but I think we'd want the change recorded in this repo, rather than just manually updated in AWS UI https://gitlab.ci.uktrade.digital/webops/terraform-tools

**Review by yusufsheiqh — APPROVED** [review]
@gabelton @JohnStainsby Hey both - this step has been simply commented out of the build project and so there shouldn't be any need to update the `terraform-tools` repo as this build project has still been running. I have confirmed that this step is simply skipped and continues to run as a build in AWS.

**Comment by JohnStainsby** [comment]
@gabelton 
Related CodeBuild changes https://gitlab.ci.uktrade.digital/webops/terraform-tools/-/merge_requests/28

**Review by gabelton — APPROVED** [review]

**Pull request merged**
